### 1. 인증 코드 보내기
POST http://localhost:30000/api/v1/auth/email/send-code
Content-Type: application/json

{
  "email": "optional94@naver.com"
}

### 2. 이메일 인증 코드 인증하기
POST http://localhost:30000/api/v1/auth/email/verify-code
Content-Type: application/json

{
  "email": "optional94@naver.com",
  "code": "562410"
}



